### ISSUE TITLE
issue with some minql-plugins

### ISSUE THREAD

**Issue by vickharitonov** [MinoMino/minqlx#106]
hello, have the same issue when loading some of the minqlx-plugins. sets.py for example:
```
(09:23:22) [INFO @ minqlx.load_plugin] Loading plugin 'sets'...
(09:23:22) [ERROR @ minqlx.sets.log_exception] Traceback (most recent call last):
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "minqlx.zip/minqlx/_core.py", line 351, in load_plugin
(09:23:22) [ERROR @ minqlx.sets.log_exception]     module = importlib.import_module("{}.{}".format(plugins_dir, plugin))
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
(09:23:22) [ERROR @ minqlx.sets.log_exception]     return _bootstrap._gcd_import(name[level:], package, level)
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "<frozen importlib._bootstrap_external>", line 851, in exec_module
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "<frozen importlib._bootstrap_external>", line 988, in get_code
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "<frozen importlib._bootstrap_external>", line 918, in source_to_code
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
(09:23:22) [ERROR @ minqlx.sets.log_exception]   File "/home/ql/./minqlx-plugins/sets.py", line 7
(09:23:22) [ERROR @ minqlx.sets.log_exception]     <!DOCTYPE html>
(09:23:22) [ERROR @ minqlx.sets.log_exception]     ^
(09:23:22) [ERROR @ minqlx.sets.log_exception] SyntaxError: invalid syntax
```

**Comment by vickharitonov** [comment]
i found a solution ) I've download plugins incorrectly
