### ISSUE TITLE
bug: frame hook running when starting map

### ISSUE THREAD

**Issue by em92** [MinoMino/minqlx#107]
```
(15:43:31) [DEBUG @ minqlx.handle_console_print] ----------------------
(15:43:31) [DEBUG @ minqlx.handle_console_print] 31964 files in pk3 files
(15:43:31) [DEBUG @ minqlx.handle_console_print] Loading dll file qagame
(15:43:31) [DEBUG @ minqlx.handle_console_print] Sys_LoadDll(qagame) found **dllEntry** at  0x7f7d74ec1180
(15:43:31) [DEBUG @ minqlx.handle_console_print] Sys_LoadDll(qagame) succeeded!
(15:43:31) [DEBUG @ minqlx.handle_console_print] Sys_SetModuleOffset: qagame 0x7F7D74EC1180
(15:43:31) [DEBUG @ minqlx.handle_console_print] ------- Game Initialization -------
(15:43:31) [DEBUG @ minqlx.handle_console_print] gamename: baseqz
(15:43:31) [DEBUG @ minqlx.handle_console_print] gamedate: May 25 2016
(15:43:31) [DEBUG @ minqlx.handle_console_print] initializing access list...
(15:43:31) [DEBUG @ minqlx.handle_console_print] loaded 6 steam ids into the access list
(15:43:31) [DEBUG @ minqlx.handle_console_print] Not logging to disk.
(15:43:31) [DEBUG @ minqlx.handle_console_print] WARNING: no info_player_intermission
(15:43:31) [DEBUG @ minqlx.handle_console_print] 0 teams with 0 entities
(15:43:31) [DEBUG @ minqlx.handle_console_print] 0 items registered
(15:43:31) [DEBUG @ minqlx.handle_console_print] -----------------------------------
(15:43:31) [ERROR @ minqlx.log_exception] Traceback (most recent call last):
(15:43:31) [ERROR @ minqlx.log_exception]   File "minqlx.zip/minqlx/_handlers.py", line 209, in handle_frame
(15:43:31) [ERROR @ minqlx.log_exception]     frame_tasks.run(blocking=False)
(15:43:31) [ERROR @ minqlx.log_exception]   File "/usr/lib/python3.5/sched.py", line 147, in run
(15:43:31) [ERROR @ minqlx.log_exception]     action(*argument, **kwargs)
(15:43:31) [ERROR @ minqlx.log_exception]   File "./minqlx-plugins/balance.py", line 234, in handle_ratings_fetched
(15:43:31) [ERROR @ minqlx.log_exception]     callback(players, channel, *args)
(15:43:31) [ERROR @ minqlx.log_exception]   File "./minqlx-plugins/balance.py", line 535, in callback_ratings
(15:43:31) [ERROR @ minqlx.log_exception]     gt = self.game.type_short
(15:43:31) [ERROR @ minqlx.log_exception] AttributeError: 'NoneType' object has no attribute 'type_short'
(15:43:31) [DEBUG @ minqlx.handle_console_print] -----------------------------------
(15:43:31) [DEBUG @ minqlx.dispatch] map('asylum', 'ca')
(15:43:31) [DEBUG @ minqlx.dispatch] new_game()
(15:43:36) [DEBUG @ minqlx.dispatch] player_spawn(Player(0:'UnNamedPlayer':76561198154317273),)
(15:43:36) [DEBUG @ minqlx.dispatch] player_loaded(Player(0:'UnNamedPlayer':76561198154317273),)
(15:43:36) [DEBUG @ minqlx.dispatch] player_spawn(Player(2:'1':76561198152482639),)
(15:43:36) [DEBUG @ minqlx.dispatch] player_loaded(Player(2:'1':76561198152482639),)
(15:43:36) [DEBUG @ minqlx.dispatch] player_spawn(Player(3:'RailingAsshole':76561197960401021),)
(15:43:36) [DEBUG @ minqlx.dispatch] player_loaded(Player(3:'RailingAsshole':76561197960401021),)
(15:43:36) [DEBUG @ minqlx.dispatch] player_spawn(Player(1:'Krypa':76561198144307152),)
(15:43:36) [DEBUG @ minqlx.dispatch] player_loaded(Player(1:'Krypa':76561198144307152),)
```
Reported by @lonewulfa via  https://gist.github.com/lonewulfa/00577163cbef2ea556ad990b5ab3d789

**Comment by em92** [comment]
Fixed via https://github.com/MinoMino/minqlx/commit/065fa21062169101d596687f27e6af2299d1bbce
