### ISSUE TITLE
minqlx exception errors, what do they mean?

### ISSUE THREAD

**Issue by mzryz** [MinoMino/minqlx#127]
Hi there,

This is the first time I've ever tried setting up a QL server & minqlx. I am getting these errors after starting my server:

```-----------------------------------
[minqlx.late_init] INFO: Loading preset plugins...
[minqlx.load_plugin] INFO: Loading plugin 'plugins_manager'...
[minqlx] ERROR @ python_dispatchers.c:164 in NewGameDispatcher:
[minqlx] PyObject_CallFunction() returned NULL.
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 442, in handle_console_print
[minqlx.log_exception] ERROR:     minqlx.get_logger().debug(text.rstrip("\n"))
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 113, in get_logger
[minqlx.log_exception] ERROR:     return logging.getLogger("minqlx")
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.8/logging/__init__.py", line 2025, in getLogger
[minqlx.log_exception] ERROR:     return Logger.manager.getLogger(name)
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 237, in handle_new_game
[minqlx.log_exception] ERROR:     minqlx.late_init()
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 461, in late_init
[minqlx.log_exception] ERROR:     load_preset_plugins()
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 337, in load_preset_plugins
[minqlx.log_exception] ERROR:     load_plugin(p)
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 350, in load_plugin
[minqlx.log_exception] ERROR:     raise PluginLoadError("No such plugin exists.")
[minqlx.log_exception] ERROR: minqlx._core.PluginLoadError: No such plugin exists.
Hitch warning: 1487 msec frame time
```

What could the problem be? Using Ubuntu 20.04 and Python 3.8.10 (installed as per wiki instructions)

**Comment by mzryz** [comment]
And some more:
```[minqlx.late_init] INFO: Loading preset plugins...
[minqlx.late_init] INFO: Loading preset plugins...
[minqlx.late_init] INFO: Loading preset plugins...
[minqlx.late_init] INFO: Loading preset plugins...
[minqlx.load_plugin] INFO: Loading plugin 'plugins_manager'...
[minqlx.load_plugin] INFO: Loading plugin 'plugins_manager'...
[minqlx.load_plugin] INFO: Loading plugin 'plugins_manager'...
[minqlx.load_plugin] INFO: Loading plugin 'plugins_manager'...
[minqlx] ERROR @ python_dispatchers.c:164 in NewGameDispatcher:
[minqlx] PyObject_CallFunction() returned NULL.
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 209, in handle_frame
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 209, in handle_frame
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 209, in handle_frame
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 209, in handle_frame
[minqlx.log_exception] ERROR:     frame_tasks.run(blocking=False)
[minqlx.log_exception] ERROR:     frame_tasks.run(blocking=False)
[minqlx.log_exception] ERROR:     frame_tasks.run(blocking=False)
[minqlx.log_exception] ERROR:     frame_tasks.run(blocking=False)
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 237, in handle_new_game
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 237, in handle_new_game
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 237, in handle_new_game
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 237, in handle_new_game
[minqlx.log_exception] ERROR:     minqlx.late_init()
[minqlx.log_exception] ERROR:     minqlx.late_init()
[minqlx.log_exception] ERROR:     minqlx.late_init()
[minqlx.log_exception] ERROR:     minqlx.late_init()
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 461, in late_init
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 461, in late_init
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 461, in late_init
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 461, in late_init
[minqlx.log_exception] ERROR:     load_preset_plugins()
[minqlx.log_exception] ERROR:     load_preset_plugins()
[minqlx.log_exception] ERROR:     load_preset_plugins()
[minqlx.log_exception] ERROR:     load_preset_plugins()
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 337, in load_preset_plugins
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 337, in load_preset_plugins
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 337, in load_preset_plugins
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 337, in load_preset_plugins
[minqlx.log_exception] ERROR:     load_plugin(p)
[minqlx.log_exception] ERROR:     load_plugin(p)
[minqlx.log_exception] ERROR:     load_plugin(p)
[minqlx.log_exception] ERROR:     load_plugin(p)
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 350, in load_plugin
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 350, in load_plugin
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 350, in load_plugin
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 350, in load_plugin
[minqlx.log_exception] ERROR:     raise PluginLoadError("No such plugin exists.")
[minqlx.log_exception] ERROR:     raise PluginLoadError("No such plugin exists.")
[minqlx.log_exception] ERROR:     raise PluginLoadError("No such plugin exists.")
[minqlx.log_exception] ERROR:     raise PluginLoadError("No such plugin exists.")
[minqlx.log_exception] ERROR: minqlx._core.PluginLoadError: No such plugin exists.
[minqlx.log_exception] ERROR: minqlx._core.PluginLoadError: No such plugin exists.
[minqlx.log_exception] ERROR: minqlx._core.PluginLoadError: No such plugin exists.
[minqlx.log_exception] ERROR: minqlx._core.PluginLoadError: No such plugin exists.```

**Comment by em92** [comment]
Typo in qlx_plugins cvar. There is no plugins_manager, but there is plugin_manager (without S letter)

**Comment by mzryz** [comment]
Thanks, just turned out I needed to be more careful with what plugins I specify in server.cfg and what I ACTUALLY have in the miniqlx plugins directory. All sorted thank you!
