### ISSUE TITLE
Configstrings are unreliable.

### ISSUE THREAD

**Issue by MinoMino** [MinoMino/minqlx#13]
```
(11:06:06) [ERROR @ minqlx.ban.log_exception] Traceback (most recent call last):
(11:06:06) [ERROR @ minqlx.ban.log_exception]   File "minqlx.zip/minqlx/_events.py", line 79, in dispatch
(11:06:06) [ERROR @ minqlx.ban.log_exception]     res = handler(*self.args, **self.kwargs)
(11:06:06) [ERROR @ minqlx.ban.log_exception]   File "./minqlx-plugins/ban.py", line 84, in handle_player_disconnect
(11:06:06) [ERROR @ minqlx.ban.log_exception]     teams = self.teams()
(11:06:06) [ERROR @ minqlx.ban.log_exception]   File "minqlx.zip/minqlx/_plugin.py", line 400, in teams
(11:06:06) [ERROR @ minqlx.ban.log_exception]     res[p.team].append(p)
(11:06:06) [ERROR @ minqlx.ban.log_exception]   File "minqlx.zip/minqlx/_player.py", line 204, in team
(11:06:06) [ERROR @ minqlx.ban.log_exception]     return minqlx.TEAMS[int(self["t"])]
(11:06:06) [ERROR @ minqlx.ban.log_exception]   File "minqlx.zip/minqlx/_player.py", line 121, in __getitem__
(11:06:06) [ERROR @ minqlx.ban.log_exception]     return self.cvars[key]
(11:06:06) [ERROR @ minqlx.ban.log_exception] KeyError: 't'
```

**Comment by MinoMino** [comment]
67d0b919ee54892862a07c59a267f456408defbc tries to deal with this. If someone wants to try it, then that'd be cool.

**Comment by MinoMino** [comment]
Looks good.
