### ISSUE TITLE
locale.error with installing minqlx

### ISSUE THREAD

**Issue by jamesla** [MinoMino/minqlx#39]
This is a fresh server and followed instructions exactly fails on final step with locale error. Ubuntu 14.04. Any idea what is happening?

james@prop:~/steamapps/common/qlds$ sudo python3.5 -m pip install -r minqlx-plugins/requirements.txt
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pip/__main__.py", line 19, in <module>
    sys.exit(pip.main())
  File "/usr/local/lib/python3.5/dist-packages/pip/**init**.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 595, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by jamesla** [comment]
fixed it with:

```
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales
```
