### ISSUE TITLE
UnicodeDecodeError 

### ISSUE THREAD

**Issue by rulex** [MinoMino/minqlx#4]
this also crashed the ql server :smile:  but they are pushing a fix out soon

```
broadcast: print "❤❤ ОДЕЯЛА и ПОДУШКИ 7 connected\n"
[minqlx.log_exception] ERROR: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 45: invalid continuation byte
[minqlx.log_exception] ERROR:
[minqlx.log_exception] ERROR: During handling of the above exception, another exception occurred:
[minqlx.log_exception] ERROR:
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR:   File "minqlx/minqlx/_handlers.py", line 169, in handle_set_configstring
[minqlx.log_exception] ERROR:     res = minqlx.EVENT_DISPATCHERS["set_configstring"].dispatch(index, value)
[minqlx.log_exception] ERROR: SystemError: PyEval_EvalFrameEx returned a result with an error set
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR:   File "minqlx/minqlx/_zmq.py", line 62, in keep_receiving
[minqlx.log_exception] ERROR:     stats = self.socket.recv_json(zmq.NOBLOCK)
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/site-packages/zmq/sugar/socket.py", line 470, in recv_json
[minqlx.log_exception] ERROR:     return jsonapi.loads(msg, **kwargs)
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/site-packages/zmq/utils/jsonapi.py", line 54, in loads
[minqlx.log_exception] ERROR:     s = s.decode('utf8')
[minqlx.log_exception] ERROR: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 131: invalid continuation byt
```

**Comment by MinoMino** [comment]
Yup, your pull request fixed some variations of this bug I saw on another server too. Thanks.
